### ISSUE TITLE
Dodo helper and costregener crash, and map dropper crashes randomly。

### ISSUE THREAD

**Issue by Ic-any** [MyShiLingStar/ACNHPokerCore#12]
Hello, I found some software problems while using the latest R20 version, such as the random crash of map dropper caused by dragging the small map in the upper left corner too fast. I need some time to test this problem and send you the video attachment. Also, the cost regen of Dodo helper and regenerator will crash. This is not random. For example, after I click the star buttopper left corner too fast. I need some time to test this problem and send you the video attachment. Also, the cost regen of Dodo helper and regenerator will crash. This is not random. For example, after I click the star button of Dodo helper, the software will crash and close directly. I want to ask if you have a good solution. Thank you! I want to ask if you have a good solution. Thank you!

![image](https://user-images.githubusercontent.com/92638461/168423517-ec0c0cfa-6e6f-4929-8672-9286f7558560.png)

**Comment by MyShiLingStar** [comment]
For the first bug, it's extremely random and rare.
Sometimes I can drag the map very long time without any problem.
Other times it might crash as soon as I move the map.

https://user-images.githubusercontent.com/816502/168427661-e24aa44f-0c3a-4930-b5f0-7b1860cacf2f.mp4

I have added many checks and locks to try to prevent it. But I still cannot be 100% sure it will not happen again.
I believe there might be some bug in the "Windows Form app" that only Microsoft can fix...
Please try to update to R21 and see if that fixes the issue for you.
It should be available very soon.


As for the second bug, you need to show me exactly where it happens in order to identify the problem.

https://user-images.githubusercontent.com/816502/168427965-a703313b-99a2-461c-ad23-bcc9133d9497.mp4

,

**Comment by Ic-any** [comment]
I recorded a video. I don't know why. I can't upload it to GitHub for you. It seems that the video recorded by NVIDIA is too large.

**Comment by Ic-any** [comment]
I'll try to suppress it, or I hope you can point out what I need to provide you.

**Comment by Ic-any** [comment]
Using map dropper, you can use the up, down, left and right direction keys to move, which may not be easy to crash,
Maybe this is the first solution.

**Comment by Ic-any** [comment]
https://user-images.githubusercontent.com/92638461/168457873-ba146ee6-67a4-420b-991b-269abbf9b1ff.mp4
![image](https://user-images.githubusercontent.com/92638461/168457875-ddc4fa42-592b-4296-b117-0d807b85d549.png)

**Comment by Ic-any** [comment]
I took a screenshot and found that it shows that please recover later, and then the software is disconnected from switch.

**Comment by MyShiLingStar** [comment]
Oh, I see your problem.
If you want BOTH dodo helper and map regen to work together, you need to enable dodo helper inside the map regen menu.
![image](https://user-images.githubusercontent.com/816502/168458231-abbee5e1-f7e2-4543-b0f3-2eb6179323f2.png)


The dodo helper that is on the main menu is used for the Freezer.

There are two ways to do map regen:
1. The old one: Map regenerator. Item regen is controlled by Poker. It allows the ignore empty space (Moogle Regenja). But require Poker to be running all time and monitoring everything.
This needs the special dodo helper in the same menu to work with.

2. The new one: The Freezer. Item regen is handled on the Switch itself. You can close Poker after the freeze and the item regen will still work.
This can use the main menu standalone dodo help.

**Comment by Ic-any** [comment]
It can be like this, thank you! I wish you a happy life!

**Comment by Ic-any** [comment]
Then close the topic. Thank you for your patience
