### ISSUE TITLE
Could NOT get my switch to connect with Win 11

### ISSUE THREAD

**Issue by FarkieBear** [MyShiLingStar/ACNHPokerCore#2]
Today I spent about 10 hours troubleshooting my switch, network, computer, files, etc., with help from the discord with no luck whatsoever. I turned off firewalls, set to private network. The program was considering an issue between sys botbase and my network. Nothing fixed it. 

Borrowed my partner's pc running windows 10, downloaded ACNHpokercore, worked first try.

Windows 11 also flagged poker as a PUP, and windows 10 did not.

Not sure if there's anything on your end to solve this, but I would love to use Poker on my PC whenever possible.

Thanks!!

**Comment by MyShiLingStar** [comment]
First, it is not the problem of Windows 11. Many testing has been done on both Windows 10 and 11. It runs fine.
![image](https://user-images.githubusercontent.com/816502/154837196-9f46c16e-7485-4a0b-b1b7-68cbe6d945a4.png)

Second, homebrew software gets flagged as PUP all the time. Here is the VirusTotal result if you do not trust it.
I have worked extensively in the new framework in order to make sure anti-virus software does not give false positives again.
The binary file (.exe) is built by Azure pipeline using Microsoft's server. 
If you still do not trust the software, you can build it yourself using Visual Studio 2022.
![image](https://user-images.githubusercontent.com/816502/154837169-2d7b6b86-6508-4a7a-aecf-d6155b316aab.png)

As for your connection problem, since both "ping" and "telnet" commands do not work on your computer, you should try to do a "Network reset". Reboot your computer after the reset.
![image](https://user-images.githubusercontent.com/816502/154837438-404bec50-b9a7-412f-bac6-7db523df97b3.png)

Once your computer has rebooted, Connect to your Wifi once again and try the "ping" and "telnet" commands.

**Comment by switchtonite** [comment]
Hello where can i get the latest file for 2.05?

**Comment by MyShiLingStar** [comment]
Please try not to hijack other people's issues.

The frontpage already contains the download link :
![image](https://user-images.githubusercontent.com/816502/154837886-08d15ec9-b1cc-4ed5-a041-92699fd24d08.png)

If you still can not see it, please click [HERE](https://berichan.github.io/GetNHSE/?org=MyShiLingStar&proj=ACNHPokerCore&projurl=https://github.com/MyShiLingStar/ACNHPokerCore)

**Comment by FarkieBear** [comment]
> First, it is not the problem of Windows 11. Many testing has been done on both Windows 10 and 11. It runs fine. ![image](https://user-images.githubusercontent.com/816502/154837196-9f46c16e-7485-4a0b-b1b7-68cbe6d945a4.png)
> 
> Second, homebrew software gets flagged as PUP all the time. Here is the VirusTotal result if you do not trust it. I have worked extensively in the new framework in order to make sure anti-virus software does not give false positives again. The binary file (.exe) is built by Azure pipeline using Microsoft's server. If you still do not trust the software, you can build it yourself using Visual Studio 2022. ![image](https://user-images.githubusercontent.com/816502/154837169-2d7b6b86-6508-4a7a-aecf-d6155b316aab.png)
> 
> As for your connection problem, since both "ping" and "telnet" commands do not work on your computer, you should try to do a "Network reset". Reboot your computer after the reset. ![image](https://user-images.githubusercontent.com/816502/154837438-404bec50-b9a7-412f-bac6-7db523df97b3.png)
> 
> Once your computer has rebooted, Connect to your Wifi once again and try the "ping" and "telnet" commands.

I just reset my network settings, rebooted my computer, and attempted to ping/telnet/connect to Poker with the same issue. Other computer still works just fine.

**Comment by MyShiLingStar** [comment]
Alright, let's try the extreme method.
Hold the "Shift" button on your keyboard and click "Restart"
![image](https://user-images.githubusercontent.com/816502/154845974-92e895d7-14c7-4f48-8d7e-68a38eef10ef.png)

Hold "Shift" until you see the following screen
![image](https://user-images.githubusercontent.com/816502/154846026-591dfde3-c897-4659-b1fa-4faf15c7b657.png)

Select Troubleshoot -> Advanced options -> Startup Settings ->Restart
![image](https://user-images.githubusercontent.com/816502/154846053-55e9d059-693c-4d06-8d4b-dbc8ed906750.png)

Once you see the following screen, press "5" on your keyboard to select "Enable Safe Mode with Networking"
![image](https://user-images.githubusercontent.com/816502/154846083-c48af493-10fa-4f96-9636-6dd79c0368e5.png)

Once you boot into Safe Mode, open some websites and confirm you can still connect to the internet.
![image](https://user-images.githubusercontent.com/816502/154846578-d96712a2-b050-4447-83e1-94c153bc77fe.png)

Try the "ping" and "telnet" commands here in Safe Mode.

If those works, You can then try connecting Poker in Safe Mode.
![image](https://user-images.githubusercontent.com/816502/154847217-6a45547c-8d36-4096-917a-00b94b98b7fa.png)

**Comment by FarkieBear** [comment]
I'm currently just resetting windows 11 entirely, but if that doesn't work, I'll do what you mentioned above. I'll keep you updated!

**Comment by FarkieBear** [comment]
Okay, there must have been a setting somewhere that I had messed with when I set up Windows 11 on my PC. Reinstalling the OS worked for me. 

Thanks for your help and time! I appreciate it. Keep up the good work and stay safe!
