### ISSUE TITLE
How should I use .nhbs files

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#28]
Is diy[a-z].nhbs all DIY under the save folder in the directory? How should I use it?

**Comment by z1006670445** [comment]
I want to fill all the diys on the map. Is there any faster way?

**Comment by MyShiLingStar** [comment]
In `Map Dropper` -> `Remove Items...` -> `Bulk Spawn`  

![image](https://user-images.githubusercontent.com/816502/180917599-63fa0c9a-1e9b-484c-8771-1b0fbde449ab.png)

Select the `.nhbs/.nhi` file -> Type the `Height` of the spawn area -> `Preview` -> `Spawn`.

Due to how the item memory is stored, please be reminded that the item order will go always be `TOP to DOWN first, then LEFT to RIGHT/RIGHT to LEFT`.

**Comment by z1006670445** [comment]
Thank you very much.I have learned it.
