### ISSUE TITLE
What is the reason for this error

### ISSUE THREAD

**Issue by z1006670445** [MyShiLingStar/ACNHPokerCore#35]
What is the reason for this error

The frequency is very high

Is there a solution?

There is another person on the island. The switch network is OK

![NSJY }}29Z{~E7~EVWX8A`Y](https://user-images.githubusercontent.com/35718635/185037571-03db477b-75d0-4a51-958b-070d5a22a0ca.png)
![UZ1 {_~QID G{8CM3NGV}D6](https://user-images.githubusercontent.com/35718635/185037582-f177afef-ee66-4b30-9f83-46f307c68e29.png)

![QQ截图20220821134057](https://user-images.githubusercontent.com/35718635/185777356-199a8cc3-b905-4f61-adee-0340b81442b2.png)

**Comment by MyShiLingStar** [comment]
When regen is activated, you should try not to use the other part of the program too much.
Sys-botbase can only handle one thing at a time, it might get overwhelmed and time out because the response takes too long.

If you want to do some inventory/map/villager editing, you should stop the regen first. Restart the regen once you are done with the other editing.
