### ISSUE TITLE
Water on beaches built using Bulldozer

### ISSUE THREAD

**Issue by rebeccarothschild** [MyShiLingStar/ACNHPokerCore#38]
Hello!

I'm using the Bulldozer tool in the Acre tab to redesign my island layout. In certain parts of the beaches, water is overlaying on the sand and it's causing glitchiness as it loads. Do you know how can I fix this? I also noticed all the acre names begin with "FldOut" - what does that mean?

Thanks for the tool, I'm really enjoying it!

**Comment by MyShiLingStar** [comment]
![image](https://user-images.githubusercontent.com/816502/189337684-ea30b95b-ce01-4ebd-a9d5-81736153b44e.png)

Beach acres can not be next to each other, they must have at least one sea acre in between.

And different sea acres also display differently. Some will actually show more water outside of that 16x16 area.
Since different people have different maps, you will need to try out other sea acres yourself.
A good starting point is to use sea acre 289 first. Change it with another one if you are not happy with how it looks.
It's a trial and error process.

**Comment by rebeccarothschild** [comment]
Ooo ok thanks for the quick response! Closing issue.
