### ISSUE TITLE
Continuously getting the 5318008 Error

### ISSUE THREAD

**Issue by kaanna** [MyShiLingStar/ACNHPokerCore#39]
I've been trying to install pokercore for the past two days, and I keep getting the 5318008 error. My home button glows upon start-up, Sys-bot is in the correct folder, and everything is how it should be (including my IP), however the error persists. I'm not sure what I'm doing wrong, and any help would be of appreciation.

**Comment by MyShiLingStar** [comment]
That usually means your network connection on port 6000 is blocked by something.
Some school or hotel network has extra security measures which might cause the problem.
It could also be a firewall or antivirus software on your computer. 
Or it could be the built-in firewall that comes with your Wifi access point or router.


The easiest way to test this is to use your phone to set up another network so that you can bypass your old network.
1. Use your phone to set up a Wifi hotspot. Both Apple and Android phones should be able to.
2. Connect both your PC and your Nintendo Switch to that Wifi hotspot.
3. Check your Nintendo Switch for the new IP address.
4. Retry the connection on ACNHPokerCore using the new IP address.

If the above works, it would confirm that the old network you were using is indeed blocked by something.

**Comment by MyShiLingStar** [comment]
Try the `ping` and `telnet` tests on your PC.
You can paste your result in the comment.

![ping](https://user-images.githubusercontent.com/816502/190203196-c7018dec-8928-4a08-b24c-3922602d375f.png)

**Comment by kaanna** [comment]
> Try the `ping` and `telnet` tests on your PC. You can paste your result in the comment.
> 
> ![ping](https://user-images.githubusercontent.com/816502/190203196-c7018dec-8928-4a08-b24c-3922602d375f.png)

Turning on the telnet client worked! I was able to connect to poker core, and it’s working perfectly. Thank you so much for the help.
