### ISSUE TITLE
Using incorrect values instead of intended ones

### ISSUE THREAD

**Issue by ThatRoadRunnerfan727** [MyShiLingStar/ACNHPokerCore#69]
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/68831086/3cfa67d5-625e-49bc-8f24-84b8ba52796a)

**Comment by MyShiLingStar** [comment]
Ram Shifting. Your game data has been shifted to a different location.
This usually happens when you have unnecessary sys modules occupying the memory.
For example: `0000000000534C56 : SaltyNX` has been known to cause ram shifting.

Remove any unnecessary sys-modules in your `atmosphere/contents` folder and try again.

---
Or

You can also try the `experimental RAM address shifting workaround`

1. Click the Gear icon to open the config menu.
2. Disable Validation
3. Close the config menu and then connect.
4. You will most likely get garbage data. Don't worry about it.
5. In game, empty your character inventory.
6. Shake some trees and pick up exactly 3 tree branches in your first inventory slot.
7. Resize the poker window at the bottom and click the Chase button then wait.
8. If you are lucky, the program would let you know if it can locate your inventory in ram.

![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/afcf89d8-616f-4326-ada3-8476d57f6624)

**Comment by ThatRoadRunnerfan727** [comment]
wow! thanks so much for the tips!

**Comment by ThatRoadRunnerfan727** [comment]
thank you so much! Please somehow add this in!!!
