### ISSUE TITLE
Usb Support?

### ISSUE THREAD

**Issue by oyasumiiisama** [MyShiLingStar/ACNHPokerCore#7]
I've found that there doesn't appear to be any support for usb in this new version of poker. This is a problem for me, as I don't have access to the internet at the moment, nor do I have access to a cable to connect my phone and switch, so acnhmobilespawner is out of the question. Am I missing something? If not, are there any alternatives with USB support?

**Comment by MyShiLingStar** [comment]
USB-botbase does not work on the new firmware 14.0.0.
And I don't see anyone picking up the project at the moment...
If someone updates that, I would try to add the USB support back.

**Comment by MyShiLingStar** [comment]
I have added the basic USB support in the latest build. Please be reminded that it is still limited to the basic function of poker.
And since I do not have much time to test everything at the moment, please let me know if something does not work.

You will need to use the hybrid version of sys-usb-botbase by Koi-3088 at [HERE](https://github.com/Koi-3088/sys-usb-botbase/releases/tag/v2.1-hybrid)

Make sure to change the file "config.cfg" in "atmosphere\contents\430000000000000B\" to **usb**
in order to use USB connection. The default is **wifi**.
