### ISSUE TITLE
after connecting to the switch, poker shows invalid datas

### ISSUE THREAD

**Issue by sir1st** [MyShiLingStar/ACNHPokerCore#71]
after connecting to the switch, poker shows invalid datas. The screenshot shows like below:
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/23466852/da9c1cce-d54e-4783-9a8f-551de4f33f5e)
the game version is v2.0.6. can anyone offer some help?

**Comment by sir1st** [comment]
![Uploading image.png…]()

**Comment by MyShiLingStar** [comment]
Ram Shifting. Your game data in memory has been shifted to a different location.
This usually happens when you have unnecessary sys modules occupying the memory.
For example: `0000000000534C56 : SaltyNX` has been known to cause ram shifting.

Please remove any unnecessary sys-modules in your `atmosphere/contents` folder and try again.

---
Or

You can also try the `experimental RAM address shifting workaround`

1. Click the Gear icon to open the config menu.
2. Disable Validation
3. Close the config menu and then connect.
4. You will get the same garbage data. Don't worry about it.
5. In game, empty your character inventory.
6. Shake some trees and pick up exactly 3 tree branches in your first inventory slot.

![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/2b6916f5-d9e0-495c-9e16-d32933a03283)

7. Resize the poker window at the bottom and click the Chase button then wait.

![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/816502/afcf89d8-616f-4326-ada3-8476d57f6624)

8. If you are lucky, the program would let you know if it can locate your inventory in ram.

**Comment by sir1st** [comment]
thanks, the problem gets solved
