### ISSUE TITLE
Request 🙂

### ISSUE THREAD

**Issue by typative** [MyShiLingStar/ACNHPokerCore#86]
Hi again,

I hope this is okay. I didn't see another place to put in for a request.

I was wondering though.. if sometime, you could also add in NPC villagers in the Villagers tab please? 

I have a Katie mod which replaces Katt. However, when using that mod, I can't fly out and I can't have visitors.. 

So I wish there could be a way for you to add them in Poker somehow, even if it means we have to choose which villager we're replacing with or something.

**Comment by MyShiLingStar** [comment]
Not possible. 
Kaite does not have any island residential data. Including dialogs, house data, clothing ... etc.
Poker could only work by manipulating data that already exists in the game. 
It cannot generate new extra data and create a new villager in runtime.

Using a mod that adds the extra data is the correct way to do it. 
Usually by extracting the Katie model and replacing one of the existing villagers.

A model replacement should not affect your ability to use the online services.
Your problem most likely lies in the fact that the mod includes some outdated files. 
Likely because it was created before the release of the latest game version 2.0.6.
Updating the mod to use the latest file from version 2.0.6 should fix the problem.
(To be more specific, the "String_EUen.sarc.zs"/"String_USen.sarc.zs" file is outdated.)

I tried to find the Kaite mod by jadduck/Wrothly but I didn't get much information about it.
You could try to contact the author and see if they are willing to update it.
![image](https://github.com/user-attachments/assets/551fe2f4-0013-4d3c-9dea-03cdca496b17)

**Comment by typative** [comment]
LoL aww, see, she's so freaking cute!!
